# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9526f5f6f5cb22ba1c15e0cbd3bc23249acd5dc8855b456cd3a1e25608428ddfee7d6d7672f1911e8fe42102f0a42213d4d7c2f9ce2d86c1c1cb6456edaa29a

test:
  secret_key_base: cb6ed45d1f6e13591725db850aee5326a600f7abae4d9f3145476603490a81e6009580cf0f3b82e8e9ca893f57270fa911fdb46259f3f248027415dcec9637aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
